id: I7BBB39BC
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:16:44.606213
last_modified: 2023-02-10 00:16:44.606398
source_metadata:
  title: 'MSV 6,07: Muktaka'
  language: bo
bases:
  AF39:
    base_file: AF39.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
